# Generated by Django 4.0.4 on 2022-05-12 06:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rename_rooms_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
