# Generated by Django 4.0.4 on 2022-05-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_roomimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomImage',
            new_name='room_Image',
        ),
    ]
